name: boq_app
description: A BOQ Excel to Android APK app.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.0
  csv: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/boq_data.json
